# docker-compose.yml
version: "3.5"

services:

  opsdroid:
    hostname: matrixaggregator
    image: opsdroid/opsdroid:latest
    restart: unless-stopped
    volumes:
      -  ./container:/root/.config/opsdroid